source 'http://rubygems.org'

gem 'sinatra' #, '1.3.1'

group :development do
  gem 'rspec'              #, '2.7.0'
  gem 'cucumber'           #, '1.1.3'
  gem 'capybara'           #, '1.1.2'
  # gem 'rspec-expectations' #, '2.7.0'
end

# group :test do
#   gem 'cucumber'           #, '1.1.3'
#   gem 'rspec-expectations' #, '2.7.0'
# end